### PR TITLE
Consider module stability during Swift version compatibility check

### PR DESCRIPTION
**Pull request by ffittschen**
Cherry picks the logic of the following upstream changes: https://github.com/Carthage/Carthage/pull/2902

This will allow using cached frameworks or downloading binaries from GitHub that have been built with an older Swift version than the one of the local toolchain. It considers if the frameworks have been built with module stability, i.e. `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` and the framework swift version.

Please let me know if I missed one of the places in which this should be checked, but in addition to the upstream changes I could only find these two cases:
https://github.com/nsoperations/Carthage/blob/master/Source/CarthageKit/VersionFile.swift#L217 https://github.com/nsoperations/Carthage/blob/master/Source/CarthageKit/BinaryProject.swift#L41

Regarding the comparison in the `BinaryProject` I was not really sure if it should also check for the module stability, so I held back and wanted to ask you here.

### CODE REVIEW

**Review by DerFlash — APPROVED** [review]
Works as expected!

Before PR:
```
$ carthage version
0.45.1+nsoperations

$ carthage bootstrap --platform iOS --cache-builds --no-use-binaries --verbose
*** No cache found for XXX, building with all downstream dependencies
*** Downloading binary-only dependency XXX at "https://XXX.json"
*** Downloading XXX binary at "3.0.0"
*** Installing XXX binary at "3.0.0"

error: Incompatible Swift version - framework was built with 5.1.3+d6c4ba50e84722a815542bda2b6e8a42 and the local version is 5.2.2+b85c77607b6eec8c88143d407d91763a.
```

Build from PR:
```
$ carthage bootstrap --platform iOS --cache-builds --no-use-binaries --verbose
*** No cache found for XXX, building with all downstream dependencies
*** Downloading binary-only dependency XXX at "https://XXX.json"
*** Downloading XXX binary at "3.0.0"
*** Installing XXX binary at "3.0.0"
*** Cross-referencing symbols for pre-built binaries
```

Thanks for your effort!

**Comment by DerFlash** [comment]
In my organization we'd really love to see this PR reviewed and merged, because this (missing) feature finally kind of blocks us from providing ABI stability throughout all of our frameworks while using carthage.

**Comment by hujunfeng** [comment]
Thank @ffittschen for cherry-picking the changes from upstream.

We have a binary Swift framework dependency in our project. This patch is required for us to use carthage+nsoperations. We would also love to see this PR merged.

**Comment by ffittschen** [comment]
@werner77 would it be possible for you to take a look at this PR?

**Comment by werner77** [comment]
Yes I’,m going to have a look today.

Thanks!

**Review by werner77 — APPROVED** [review]

**Comment by werner77** [comment]
I just released 0.46.0+nsoperations with this PR merged in there.

Thanks again!

**Comment by ffittschen** [comment]
Awesome, thank you!

**Comment by ObjectiveCesar** [comment]
Nice, in the name of @DerFlash and on behalf of our organisation I salute you for the merge!

**Pull request merged**
